version: '3.8'
services:

  bbs:
    image: ghcr.io/zixia/bbs
    container_name: bbs
    network_mode: bridge
    hostname: bbs.zixia.net

    # ⬇️  
    # Enable GDB in container Issue #12
    #   https://github.com/zixia/bbs/issues/12
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined

    # ⬇️  Fix invalid port specification
    #   https://github.com/docker/compose/issues/4729#issuecomment-436148318
    #   https://medium.com/@junwan01/quote-your-ports-in-docker-compose-file-34d9505999ad
    ports:
      - '22:22'
      - '23:23'
      - '2222:2222'
    expose:
      - 80
    volumes:
      - /data/bbs/:/bbs
    environment:
      TZ: "Asia/Shanghai"
      VIRTUAL_HOST: 'bbs.zixia.net,*.bbs.zixia.net,wforum.zixia.net,*.wforum.zixia.net'
      LETSENCRYPT_HOST: 'bbs.zixia.net,wforum.zixia.net'
      HTTPS_METHOD: 'noredirect'
