version: '3.8'
services:

  17fly:
    image: ghcr.io/zixia/17fly.com
    container_name: 17fly
    network_mode: bridge
    expose:
      - 80
    volumes:
      - /data/17fly.com/center/data:/var/www/center/data
      - /data/17fly.com/home/attachment:/var/www/home/attachment
      - /data/17fly.com/home/data:/var/www/home/data
      - /data/17fly.com/bbs/attachments:/var/www/bbs/attachments
      - /data/17fly.com/bbs/forumdata:/var/www/bbs/forumdata
    environment:
      - HTTPS_METHOD=noredirect
      - VIRTUAL_HOST=17fly.zixia.net
      - LETSENCRYPT_HOST=17fly.zixia.net
    env_file:
      - .env

  17mma:
    image: ghcr.io/zixia/17mma.com
    container_name: 17mma
    network_mode: bridge
    expose:
      - 80
    volumes:
      - /data/17mma.com/center/data:/var/www/center/data
      - /data/17mma.com/home/attachment:/var/www/home/attachment
      - /data/17mma.com/home/data:/var/www/home/data
      - /data/17mma.com/bbs/attachments:/var/www/bbs/attachments
      - /data/17mma.com/bbs/forumdata:/var/www/bbs/forumdata
    environment:
      - HTTPS_METHOD=noredirect
      - VIRTUAL_HOST=17mma.zixia.net
      - LETSENCRYPT_HOST=17mma.zixia.net
    env_file:
      - .env

  17paoku:
    image: ghcr.io/zixia/17paoku.com
    container_name: 17paoku
    network_mode: bridge
    expose:
      - 80
    volumes:
      - /data/17paoku.com/center/data:/var/www/center/data
      - /data/17paoku.com/home/attachment:/var/www/home/attachment
      - /data/17paoku.com/home/data:/var/www/home/data
      - /data/17paoku.com/bbs/attachments:/var/www/bbs/attachments
      - /data/17paoku.com/bbs/forumdata:/var/www/bbs/forumdata
    environment:
      - HTTPS_METHOD=noredirect
      - VIRTUAL_HOST=17paoku.zixia.net
      - LETSENCRYPT_HOST=17paoku.zixia.net
    env_file:
      - .env

  17salsa:
    image: ghcr.io/zixia/17salsa.com
    container_name: 17salsa
    network_mode: bridge
    expose:
      - 80
    volumes:
      - /data/17salsa.com/dl:/var/www/dl
      - /data/17salsa.com/center/data:/var/www/center/data
      - /data/17salsa.com/home/attachment:/var/www/home/attachment
      - /data/17salsa.com/home/data:/var/www/home/data
      - /data/17salsa.com/site/attachments:/var/www/site/attachments
      - /data/17salsa.com/site/data:/var/www/site/data
      - /data/17salsa.com/shop/data:/var/www/shop/data
      - /data/17salsa.com/shop/images:/var/www/shop/images
      - /data/17salsa.com/shop/temp:/var/www/shop/temp
      - /data/17salsa.com/wiki/data:/var/www/wiki/data
      - /data/17salsa.com/wiki/uploads:/var/www/wiki/uploads
      - /data/17salsa.com/mall/data:/var/www/mall/data
      - /data/17salsa.com/mall/temp:/var/www/mall/temp
    environment:
      - HTTPS_METHOD=noredirect
      - VIRTUAL_HOST=17salsa.com,*.17salsa.com,17salsa.net,*.17salsa.net,17salsa.org,*.17salsa.org
      - LETSENCRYPT_HOST=17salsa.com,www.17salsa.com,cdn.17salsa.com,abu.17salsa.com,17salsa.net,www.17salsa.net,17salsa.org,www.17salsa.org
    env_file:
      - .env

  ceibsmobi:
    image: ghcr.io/zixia/ceibsmobi.com
    container_name: ceibsmobi
    network_mode: bridge
    expose:
      - 80
    volumes:
      - /data/ceibsmobi.com/admin/UploadFiles:/var/www/admin/UploadFiles
    environment:
      - HTTPS_METHOD=noredirect
      - VIRTUAL_HOST=ceibsmobi.com,www.ceibsmobi.com
      - LETSENCRYPT_HOST=ceibsmobi.com,www.ceibsmobi.com
      - PHP_ERROR_REPORTING=~E_ALL
    env_file:
      - .env

  dme73:
    image: bylexus/apache-php56
    container_name: dme73
    network_mode: bridge
    expose:
      - 80
    volumes:
      - /data/dme73.zixia.net:/var/www
    environment:
      - HTTPS_METHOD=noredirect
      - VIRTUAL_HOST=dme73.zixia.net
      - LETSENCRYPT_HOST=dme73.zixia.net

