version: '3.8'
services:

  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    network_mode: bridge
    expose:
      - 80
    volumes:
      - .:/etc/nginx/
    environment:
      - HTTPS_METHOD=noredirect
      - VIRTUAL_HOST=bbs.zixia.net,wforum.zixia.net
      - LETSENCRYPT_HOST=bbs.zixia.net,wforum.zixia.net
